version: "3.9"
 
networks:
  wordpress_net:
 
volumes:
  db_data: {}
 
services:
 
  db:
    container_name: mysql
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wordpress_net
 
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    ports:
      - "8181:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1      
      MYSQL_ROOT_PASSWORD: wordpress
    networks:
      - wordpress_net
    depends_on:
      - db
 
  wordpress:
    container_name: wordpress
    image: wordpress:latest
    volumes:
      - ./docker/php.ini:/usr/local/etc/php/conf.d/wp-php.ini
      - ./wordpress:/var/www/html
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
      - wordpress_net
    depends_on:
      - db
